// API 入出力の Zod スキーマ（唯一の型定義）。実体は各 API task で追加する。

// 認証（P0-08 パスワード / P0-09 PIN）。
// ログイン識別子は orgShortId + スタッフ番号 + 認証情報。
export {
  AUTH_ERROR_CODES,
  ORG_SHORT_ID_LENGTH,
  PASSWORD_POLICY,
  PIN_POLICY,
  authErrorSchema,
  loginRequestSchema,
  loginResponseSchema,
  orgShortIdSchema,
  passwordSchema,
  pinLoginRequestSchema,
  pinLoginResponseSchema,
  pinSchema,
  staffNumberSchema,
  type AuthError,
  type AuthErrorCode,
  type LoginRequest,
  type LoginResponse,
  type PinLoginRequest,
  type PinLoginResponse,
} from "./auth.js";

// 表示中の施設の切り替え（P0-14 / P0-21 で `"ALL"` を追加）。
export {
  ALL_PROPERTIES,
  SCOPE_ERROR_CODES,
  propertyIdSchema,
  propertyScopeSchema,
  scopeErrorSchema,
  switchPropertyRequestSchema,
  switchPropertyResponseSchema,
  type PropertyScopeValue,
  type ScopeErrorCode,
  type SwitchPropertyRequest,
  type SwitchPropertyResponse,
} from "./session.js";

// 組織設定（P1-22）。施設選択画面を挟む閾値だけ（§19.4）。
export {
  PROPERTY_SELECTION_THRESHOLD,
  organizationSettingsResponseSchema,
  organizationSettingsUpdateSchema,
  propertySelectionThresholdSchema,
  type OrganizationSettingsResponse,
  type OrganizationSettingsUpdate,
} from "./organization.js";

// 施設サマリー（P0-21）。rollup テーブルからのみ組み立てる（§26 の絶対ルール）。
export {
  SEAL_IMAGE,
  TAX_ROUNDING_MODES,
  businessDateSchema,
  invoiceRegistrationNumberSchema,
  propertySummaryResponseSchema,
  propertySummarySchema,
  roomTypeCodeSchema,
  roomTypeCreateSchema,
  roomTypeListResponseSchema,
  roomTypeSummarySchema,
  roomTypeUpdateSchema,
  taxProfileUpdateSchema,
  type PropertySummary,
  type PropertySummaryResponse,
  type RoomTypeCreate,
  type RoomTypeListResponse,
  type RoomTypeSummary,
  type RoomTypeUpdate,
  type TaxProfileUpdate,
} from "./property.js";

// 清掃タスク（P1-02 〜 P1-05）。enum の語彙は PK-SPEC-P1 §2.1 を正とする。
export {
  CHECKLIST_VALUES,
  TASK_ACTIONS,
  TASK_ERROR_CODES,
  TASK_REASON_CODES,
  TASK_STATUSES,
  TASK_TYPES,
  checklistValueSchema,
  resourceIdSchema,
  roomPlanAllCheckoutRequestSchema,
  roomPlanEntrySchema,
  roomPlanImportRequestSchema,
  roomPlanUpsertRequestSchema,
  roomPlanUpsertResponseSchema,
  standardTimeEntrySchema,
  standardTimeListResponseSchema,
  standardTimeUpsertRequestSchema,
  taskActionSchema,
  myDayGroupSchema,
  myDayPropertySchema,
  myDayResponseSchema,
  myDaySummarySchema,
  taskErrorSchema,
  taskGenerateRequestSchema,
  taskGenerateResponseSchema,
  taskListResponseSchema,
  taskReasonCodeSchema,
  taskStatusSchema,
  taskSummarySchema,
  taskTransitionRequestSchema,
  taskTransitionResponseSchema,
  taskTypeSchema,
  type MyDayGroup,
  type MyDayProperty,
  type MyDayResponse,
  type MyDaySummary,
  type RoomPlanAllCheckoutRequest,
  type RoomPlanEntry,
  type RoomPlanImportRequest,
  type RoomPlanUpsertRequest,
  type RoomPlanUpsertResponse,
  type StandardTimeEntry,
  type StandardTimeListResponse,
  type StandardTimeUpsertRequest,
  type TaskActionValue,
  type TaskError,
  type TaskErrorCode,
  type TaskGenerateRequest,
  type TaskGenerateResponse,
  type TaskListResponse,
  type TaskSummary,
  type TaskTransitionRequest,
  type TaskTransitionResponse,
  type TaskTypeValue,
} from "./task.js";

// 清掃写真（P1-11）。位置情報の受け口を作らない（INV-11）。
export {
  ACCEPTED_PHOTO_MIME,
  MAX_PHOTOS_PER_TASK,
  MAX_PHOTO_BYTES,
  PHOTO_ERROR_CODES,
  PHOTO_JPEG_QUALITY,
  PHOTO_KINDS,
  PHOTO_MAX_LONG_EDGE,
  photoErrorSchema,
  photoKindSchema,
  photoUploadMetaSchema,
  taskPhotoListResponseSchema,
  taskPhotoSchema,
  taskPhotoUploadResponseSchema,
  type AcceptedPhotoMime,
  type PhotoError,
  type PhotoErrorCode,
  type PhotoKindValue,
  type PhotoUploadMeta,
  type TaskPhoto,
  type TaskPhotoListResponse,
  type TaskPhotoUploadResponse,
} from "./photo.js";

// チェックリスト（P1-06）。実施結果は 3 値（INV-22）。
export {
  CHECKLIST_LOCALES,
  checklistItemInputSchema,
  checklistLabelsSchema,
  checklistResultUpdateRequestSchema,
  checklistTemplateListResponseSchema,
  checklistTemplateSchema,
  checklistTemplateUpsertRequestSchema,
  taskChecklistResponseSchema,
  type ChecklistItemInput,
  type ChecklistResultUpdateRequest,
  type ChecklistTemplate,
  type ChecklistTemplateListResponse,
  type ChecklistTemplateUpsertRequest,
  type TaskChecklistResponse,
} from "./checklist.js";

// 検査（P2-04 / PK-SPEC-P2 §4）。**全体の判定を受け取る口を作らない**（§4.3 MUST）。
export {
  DEFECT_CODES,
  DEFECT_NOTE_MAX_LENGTH,
  GENERAL_NOTE_MAX_LENGTH,
  EMERGENCY_OVERRIDE_REASON_MAX_LENGTH,
  INSPECTION_ERROR_CODES,
  INSPECTION_ITEM_STATUSES,
  INSPECTION_QUEUE_TONES,
  INSPECTION_RESULTS,
  OVERRIDE_REASON_MAX_LENGTH,
  defectCodeSchema,
  inspectionCompleteRequestSchema,
  inspectionCompleteResponseSchema,
  inspectionDetailResponseSchema,
  inspectionErrorSchema,
  inspectionItemSchema,
  inspectionItemStatusSchema,
  inspectionItemUpdateRequestSchema,
  inspectionOverrideRequestSchema,
  inspectionOverrideResponseSchema,
  inspectionPhotoSchema,
  inspectionPhotoUploadMetaSchema,
  inspectionPhotoUploadResponseSchema,
  inspectionQueueItemSchema,
  inspectionQueueResponseSchema,
  inspectionQueueToneSchema,
  inspectionResultSchema,
  inspectionSchema,
  inspectionStartRequestSchema,
  inspectionWaitingItemSchema,
  inspectionWaitingResponseSchema,
  strandedTaskListResponseSchema,
  strandedTaskSchema,
  type DefectCodeValue,
  type Inspection,
  type InspectionCompleteRequest,
  type InspectionCompleteResponse,
  type InspectionDetailResponse,
  type InspectionError,
  type InspectionErrorCode,
  type InspectionItem,
  type InspectionItemStatusValue,
  type InspectionItemUpdateRequest,
  type InspectionOverrideRequest,
  type InspectionOverrideResponse,
  type InspectionPhoto,
  type InspectionPhotoUploadMeta,
  type InspectionPhotoUploadResponse,
  type InspectionQueueItem,
  type InspectionQueueResponse,
  type InspectionQueueToneValue,
  type InspectionResultValue,
  type InspectionStartRequest,
  type InspectionWaitingItem,
  type InspectionWaitingResponse,
  type StrandedTask,
  type StrandedTaskListResponse,
} from "./inspection.js";

// 差戻し・再清掃（P2-07 / 同 §4.5〜§4.7）。
// **合格した項目を返す口を作らない**（§4.6「差戻し項目だけ」）。
export {
  REWORK_ERROR_CODES,
  REWORK_STATUSES,
  WAIVE_REASON_MAX_LENGTH,
  WAIVE_REASON_MIN_LENGTH,
  WAIVE_ROOM_OUTCOMES,
  reworkActionRequestSchema,
  reworkActionResponseSchema,
  reworkDetailResponseSchema,
  reworkErrorSchema,
  reworkItemSchema,
  reworkPhotoSchema,
  reworkSchema,
  reworkStatusSchema,
  reworkWaiveRequestSchema,
  waiveRoomOutcomeSchema,
  type Rework,
  type ReworkActionRequest,
  type ReworkActionResponse,
  type ReworkDetailResponse,
  type ReworkError,
  type ReworkErrorCode,
  type ReworkItem,
  type ReworkPhoto,
  type ReworkStatusValue,
  type ReworkWaiveRequest,
  type WaiveRoomOutcomeValue,
} from "./rework.js";

// 証跡スナップショット（P2-08 / 同 §3.7・§6）。
// **UPDATE / DELETE の口を作らない**（§3.7 MUST）。
export {
  EVIDENCE_TYPES,
  evidenceSnapshotSchema,
  evidenceTypeSchema,
  evidenceVerifyResponseSchema,
  snapshotVerificationSchema,
  type EvidenceSnapshotSummary,
  type EvidenceTypeValue,
  type EvidenceVerifyResponse,
  type SnapshotVerificationResult,
} from "./evidence.js";

// 忘れ物・設備不具合（P2-11 / P2-12 / 同 §7・§8・§14.3）。
// **持ち主に関する入力欄が 1 つも無い**（security.md §3）。
export {
  ISSUE_CATEGORIES,
  ISSUE_ERRORS,
  ISSUE_SEVERITIES,
  ISSUE_STATUSES,
  LOST_ITEM_CATEGORIES,
  LOST_ITEM_ERRORS,
  LOST_ITEM_STATUSES,
  issueCategorySchema,
  issueCreateRequestSchema,
  issueReportSchema,
  issueSeveritySchema,
  issueStatusRequestSchema,
  issueStatusSchema,
  lostItemCategorySchema,
  lostItemCreateRequestSchema,
  lostItemSchema,
  lostItemStatusRequestSchema,
  lostItemStatusSchema,
  type IssueCategoryValue,
  type IssueCreateRequest,
  type IssueError,
  type IssueErrorCode,
  type IssueReportSummary,
  type IssueSeverityValue,
  type IssueStatusRequest,
  type IssueStatusValue,
  type LostItemCategoryValue,
  type LostItemCreateRequest,
  type LostItemError,
  type LostItemErrorCode,
  type LostItemStatusRequest,
  type LostItemStatusValue,
  type LostItemSummary,
} from "./report.js";

// 観察記録・リネン・観察設定（P3-03〜P3-07 / P3-11 / PK-SPEC-P3 §2・§4・§7）。
// **「判断」を受け取る欄が 1 つも無い**（§1.1）。判定は P4 の仕事（§0.2）。
export {
  AMENITY_ITEM_CODES,
  AMEND_REASON_MAX_LENGTH,
  AMEND_REASON_MIN_LENGTH,
  ITEM_CODES,
  LINEN_ITEM_CODES,
  MAX_OBSERVED_QTY,
  OBSERVATION_ERROR_CODES,
  OBSERVATION_NOTE_MAX_LENGTH,
  TRASH_LEVELS,
  itemCodeSchema,
  linenEntrySchema,
  linenListResponseSchema,
  linenRecordSchema,
  linenUpsertRequestSchema,
  observationAmendRequestSchema,
  observationConfigSchema,
  observationConfigUpdateRequestSchema,
  observationCountsSchema,
  observationDetailResponseSchema,
  observationErrorSchema,
  observationListResponseSchema,
  observationPropertyIdSchema,
  observationSchema,
  observationSkipRequestSchema,
  observationUpsertRequestSchema,
  observationUpsertResponseSchema,
  trashLevelSchema,
  type ItemCodeValue,
  type LinenEntry,
  type LinenListResponse,
  type LinenRecordSummary,
  type LinenUpsertRequest,
  type Observation,
  type ObservationAmendRequest,
  type ObservationConfig,
  type ObservationConfigUpdateRequest,
  type ObservationCounts,
  type ObservationDetailResponse,
  type ObservationError,
  type ObservationErrorCode,
  type ObservationListResponse,
  type ObservationSkipRequest,
  type ObservationUpsertRequest,
  type ObservationUpsertResponse,
  type TrashLevelValue,
} from "./observation.js";

// middleware 共通のエラー応答（P0-10）。**403 を足さないこと**（INV-31）。
export {
  API_ERROR_CODES,
  apiErrorSchema,
  type ApiError,
  type ApiErrorCode,
} from "./error.js";

// 日報（P2-14 / PK-SPEC-P2 §9・§14.4）。
// **削除・訂正のスキーマが無い。** 作り直しは版を上げた新しい 1 通。
export {
  dailyReportDownloadResponseSchema,
  dailyReportGenerateRequestSchema,
  dailyReportGenerateResponseSchema,
  dailyReportSchema,
  type DailyReportDownloadResponse,
  type DailyReportGenerateRequest,
  type DailyReportGenerateResponse,
  type DailyReportSummary,
} from "./dailyReport.js";

// 消耗ベースラインとデータ品質（P3-09 / P3-10 / P3-12 / PK-SPEC-P3 §5・§6）。
// **判定を返さない**（同 §0.2）。`isReliable` は統計の信頼性であって
// 観察の良し悪しではない。スタッフ別は入力率だけ（security.md §5）。
export {
  BASELINE_ERROR_CODES,
  BASELINE_EXCLUSION_REASONS,
  BASELINE_OVERRIDE_REASON_MAX_LENGTH,
  BASELINE_OVERRIDE_REASON_MIN_LENGTH,
  DATA_QUALITY_STATUSES,
  MAX_BASELINE_QTY,
  baselineErrorSchema,
  baselineExclusionReasonSchema,
  baselineListResponseSchema,
  baselineMaturitySchema,
  baselineOverrideRequestSchema,
  baselineOverrideResponseSchema,
  baselineRecomputeRequestSchema,
  baselineRecomputeResponseSchema,
  baselineSchema,
  dataQualityMonthSchema,
  dataQualityRateSchema,
  dataQualityResponseSchema,
  dataQualityStatusSchema,
  staffInputRateSchema,
  type Baseline,
  type BaselineError,
  type BaselineErrorCode,
  type BaselineExclusionReasonValue,
  type BaselineListResponse,
  type BaselineMaturitySummary,
  type BaselineOverrideRequest,
  type BaselineOverrideResponse,
  type BaselineRecomputeRequest,
  type BaselineRecomputeResponse,
  type DataQualityRate,
  type DataQualityResponse,
  type DataQualityStatusValue,
  type StaffInputRateSummary,
} from "./baseline.js";

// 稼働記録（P4-02 / PK-SPEC-P4 §2.1・§8）。
// **宿泊者に関する欄が 1 つも無い**（同 §2.1 MUST / security.md §3）。
export {
  MAX_GUEST_COUNT,
  MAX_NIGHTS,
  MAX_OCCUPANCY_CSV_LENGTH,
  MAX_RESERVATION_REF_LENGTH,
  OCCUPANCY_CHANNEL_CODES,
  OCCUPANCY_ERROR_CODES,
  OCCUPANCY_SOURCES,
  occupancyChannelCodeSchema,
  occupancyErrorSchema,
  occupancyImportRequestSchema,
  occupancyImportResponseSchema,
  occupancyListResponseSchema,
  occupancySnapshotEntrySchema,
  occupancySnapshotSchema,
  occupancySnapshotUpsertRequestSchema,
  occupancySourceSchema,
  type OccupancyChannelCodeValue,
  type OccupancyError,
  type OccupancyImportRequest,
  type OccupancyImportResponse,
  type OccupancyListResponse,
  type OccupancySnapshot,
  type OccupancySnapshotEntry,
  type OccupancySnapshotUpsertRequest,
  type OccupancySourceValue,
} from "./occupancy.js";

// 稼働照合（P4-05 / PK-SPEC-P4 §5.4）。**差異を読む口はここに無い**（P4-06 / P4-07）。
export {
  RECONCILIATION_ERROR_CODES,
  RECONCILIATION_MAX_LOOKBACK_DAYS,
  reconciliationErrorSchema,
  reconciliationRunRequestSchema,
  reconciliationRunResponseSchema,
  type ReconciliationError,
  type ReconciliationErrorCode,
  type ReconciliationRunRequest,
  type ReconciliationRunResponse,
} from "./reconciliation.js";

// 差異レポート（P4-06 / P4-07 / PK-SPEC-P4 §6）。
// **差異を作る口・消す口が無い。** 人が触れるのは状態と理由だけ。
// 3 系統は `sources` の 3 つの鍵として必ず返す（§6.2 MUST）。
export {
  FINDING_ASSIGNABLE_STATUSES,
  FINDING_ERROR_CODES,
  FINDING_FALSE_POSITIVE_CODES,
  FINDING_LIST_MAX_LIMIT,
  FINDING_RESOLUTION_CODES,
  FINDING_RESOLVED_CODES,
  FINDING_SEVERITIES,
  FINDING_STATUSES,
  RESOLUTION_NOTE_MAX_LENGTH,
  findingAccessLogSchema,
  findingAdjacentOccupancySchema,
  findingAssignableStatusSchema,
  findingCountsSchema,
  findingDetailResponseSchema,
  findingErrorSchema,
  findingHistoryEntrySchema,
  findingListResponseSchema,
  findingObservationFactSchema,
  findingOccupancyFactSchema,
  findingReferenceSchema,
  findingSeveritySchema,
  findingSignalFactSchema,
  findingSourcesSchema,
  findingStatusRequestSchema,
  findingStatusResponseSchema,
  findingStatusSchema,
  findingSummarySchema,
  type FindingAccessLog,
  type FindingAdjacentOccupancy,
  type FindingAssignableStatusValue,
  type FindingCounts,
  type FindingDetailResponse,
  type FindingError,
  type FindingErrorCode,
  type FindingFalsePositiveCodeValue,
  type FindingHistoryEntry,
  type FindingListResponse,
  type FindingObservationFact,
  type FindingOccupancyFact,
  type FindingReference,
  type FindingResolutionCodeValue,
  type FindingResolvedCodeValue,
  type FindingSeverityValue,
  type FindingSignalFact,
  type FindingSources,
  type FindingStatusRequest,
  type FindingStatusResponse,
  type FindingStatusValue,
  type FindingSummary,
} from "./finding.js";

// 業務上の入室記録（P4-10 / PK-SPEC-P4 §2.3・§4.1）。
// **業務日を受け取らない**（`enteredAt` と日締め時刻からサーバーが決める）。
export {
  ROOM_ACCESS_ACTOR_NAME_MAX_LENGTH,
  ROOM_ACCESS_ERROR_CODES,
  ROOM_ACCESS_MAX_FUTURE_DAYS,
  ROOM_ACCESS_MAX_PAST_DAYS,
  ROOM_ACCESS_NOTE_MAX_LENGTH,
  ROOM_ACCESS_PURPOSES,
  roomAccessCreateRequestSchema,
  roomAccessCreateResponseSchema,
  roomAccessErrorSchema,
  roomAccessListResponseSchema,
  roomAccessLogSchema,
  roomAccessPurposeSchema,
  type RoomAccessCreateRequest,
  type RoomAccessCreateResponse,
  type RoomAccessError,
  type RoomAccessErrorCode,
  type RoomAccessListResponse,
  type RoomAccessLogSummary,
  type RoomAccessPurposeValue,
} from "./roomAccess.js";

// ルール設定（P4-13 / PK-SPEC-P4 §2.7 / W-25）。
// **ルールの条件式を送る欄が無い。** 送れるのは有効・無効／重要度の上書き／
// 閾値の 3 つだけで、判定そのものは `packages/engine` にある。
export {
  MAX_THRESHOLD_KEYS,
  RULE_CODES,
  RULE_CONFIG_ERROR_CODES,
  ruleCodeSchema,
  ruleConfigErrorSchema,
  ruleConfigListResponseSchema,
  ruleConfigSchema,
  ruleConfigUpdateRequestSchema,
  ruleConfigUpdateResponseSchema,
  thresholdsSchema,
  type RuleCodeValue,
  type RuleConfigError,
  type RuleConfigErrorCode,
  type RuleConfigListResponse,
  type RuleConfigSummary,
  type RuleConfigUpdateRequest,
  type RuleConfigUpdateResponse,
} from "./ruleConfig.js";

// 月次監査レポート（P4-14 / PK-SPEC-P4 §7・§8）。
// **免責文を受け取る欄が無い**（§7.2 MUST）。版も持たない。
export {
  auditReportDownloadResponseSchema,
  auditReportGenerateRequestSchema,
  auditReportGenerateResponseSchema,
  auditReportMonthSchema,
  type AuditReportDownloadResponse,
  type AuditReportGenerateRequest,
  type AuditReportGenerateResponse,
} from "./auditReport.js";

// 取引先マスタと料金設定（P5-02 / P5-03 / PK-SPEC-P5 §2.1・§2.2・§9）。
// **削除の口が無い。** 無効化は isActive、料金は期間を閉じる（billing.md §2）。
export {
  BILLING_PERIOD_REVIEW_ACTIONS,
  BILLING_PERIOD_STATUSES,
  INVOICE_ITEM_CODES,
  INVOICE_STATUSES,
  PAYMENT_METHODS,
  RECEIPT_STATUSES,
  billingLineTasksResponseSchema,
  billingPeriodAgreeRequestSchema,
  billingPeriodLineCommentSchema,
  billingPeriodLineSchema,
  billingPeriodLinesResponseSchema,
  billingPeriodListResponseSchema,
  billingPeriodRejectRequestSchema,
  billingPeriodRequestReviewRequestSchema,
  billingPeriodReviewEntrySchema,
  billingPeriodReviewListResponseSchema,
  billingPeriodSummarySchema,
  billingPeriodWarningSchema,
  closingDaySchema,
  counterpartyCodeSchema,
  counterpartyCreateSchema,
  counterpartyListResponseSchema,
  counterpartySummarySchema,
  counterpartyUpdateSchema,
  invoiceCorrectRequestSchema,
  invoiceDetailResponseSchema,
  invoiceIssueRequestSchema,
  invoiceLineSchema,
  invoiceListResponseSchema,
  invoiceSummarySchema,
  invoiceTaxSummarySchema,
  paymentTermDaysSchema,
  pricingRuleCloseSchema,
  pricingRuleCreateSchema,
  pricingRuleListResponseSchema,
  pricingRuleSummarySchema,
  receiptIssueRequestSchema,
  receiptListResponseSchema,
  receiptSummarySchema,
  taxRateSchema,
  unitPriceSchema,
  type BillingLineTasksResponse,
  type BillingPeriodAgreeRequest,
  type BillingPeriodLine,
  type BillingPeriodLineComment,
  type BillingPeriodLinesResponse,
  type BillingPeriodListResponse,
  type BillingPeriodRejectRequest,
  type BillingPeriodRequestReviewRequest,
  type BillingPeriodReviewEntry,
  type BillingPeriodReviewListResponse,
  type BillingPeriodSummary,
  type CounterpartyCreate,
  type CounterpartyListResponse,
  type CounterpartySummary,
  type CounterpartyUpdate,
  type InvoiceCorrectRequest,
  type InvoiceDetailResponse,
  type InvoiceIssueRequest,
  type InvoiceLine,
  type InvoiceListResponse,
  type InvoiceSummary,
  type InvoiceTaxSummary,
  type PricingRuleClose,
  type PricingRuleCreate,
  type PricingRuleListResponse,
  type PricingRuleSummary,
  type ReceiptIssueRequest,
  type ReceiptListResponse,
  type ReceiptSummary,
} from "./billing.js";

// 組織ダッシュボード（P5-14 / PK-SPEC-P5 §7.1）。**割合を返さない。**
// 分子と分母を整数のまま返し、画面が割る（`dashboard.ts` の注記）。
export {
  LOST_ITEM_EXPIRY_WARNING_DAYS,
  monthSchema,
  orgDashboardActionsSchema,
  orgDashboardPropertySchema,
  orgDashboardResponseSchema,
  orgDashboardSummarySchema,
  type OrgDashboardActions,
  type OrgDashboardProperty,
  type OrgDashboardResponse,
  type OrgDashboardSummary,
} from "./dashboard.js";

// 清掃会社プラン（P5-15 / PK-SPEC-P5 §7.2）。**§7.1 と型を共有しない。**
// 税込（請求状況）と税抜（施設別収支）が同じ画面に並ぶ（`vendorPlan.ts` の注記）。
export {
  LOW_HOURLY_RATE_PERCENT,
  VENDOR_BILLING_STATES,
  vendorBillingRowSchema,
  vendorPlanResponseSchema,
  vendorPlanSummarySchema,
  vendorPropertyRowSchema,
  type VendorBillingRow,
  type VendorBillingState,
  type VendorPlanResponse,
  type VendorPlanSummary,
  type VendorPropertyRow,
} from "./vendorPlan.js";

// 汎用 Webhook 受信口（P6-04 / PK-SPEC-P6 §4.2）。**宿泊者の欄が 1 つも無い。**
// 未知の種類は 1 件だけ落として受信そのものは成功させる（`integration.ts` の注記）。
export {
  MAX_ACTOR_REF_LENGTH,
  MAX_DEVICE_ID_LENGTH,
  MAX_WEBHOOK_BODY_BYTES,
  MAX_WEBHOOK_EVENTS,
  SIGNAL_ACTOR_TYPES,
  SIGNAL_TYPES,
  signalActorTypeSchema,
  signalTypeSchema,
  webhookAcceptedSchema,
  webhookSignalBodySchema,
  webhookSignalEventSchema,
  type SignalTypeValue,
  type WebhookAccepted,
  type WebhookSignalBody,
  type WebhookSignalEvent,
} from "./integration.js";

// 公開 API のキー（P6-12 / PK-SPEC-P6 §6.1・§6.2）。
// **平文のトークンを受け取る欄が無い**（サーバーが採番する）。
export {
  API_SCOPE_CODES,
  MAX_API_KEY_NAME_LENGTH,
  apiKeyCreateRequestSchema,
  apiScopeSchema,
  type ApiKeyCreateRequest,
  type ApiScopeCode,
} from "./apiKey.js";

// 退避データの復元（P7-09 / PK-SPEC-P7 §9）。
// **「削除」ではなく「退避」。** 期限で読めなくなるのは復元した写し。
export {
  ARCHIVE_RESTORE_STATUS_CODES,
  archiveRestoreCreateRequestSchema,
  archiveRestoreStatusSchema,
  type ArchiveRestoreCreateRequest,
  type ArchiveRestoreRowView,
  type ArchiveRestoreStatusCode,
  type ArchiveRestoreView,
} from "./archive.js";

// 現場スタッフの登録（P7-01 / PK-SPEC-P7 §2.3 Step 5）。
// **PIN はサーバーが発行し、作成の応答で 1 回だけ返す**（DECISIONS #177）。
// 管理者のメール招待は未実装（OPEN_QUESTIONS #101）。
export {
  FIELD_STAFF_ROLES,
  fieldStaffCreateSchema,
  fieldStaffRoleSchema,
  type FieldStaffCreateRequest,
  type FieldStaffCreateResponse,
  type FieldStaffRoleValue,
} from "./user.js";

// セットアップウィザードの進行（P7-01 / PK-SPEC-P7 §2.3）。
// **スキップを状態として持つ**（「やっていない」と「やらないと決めた」は違う）。
export {
  EMPTY_SETUP_STATE,
  SETUP_STATE_VERSION,
  SETUP_STEPS,
  SETUP_STEP_STATES,
  setupCompanySchema,
  setupStateSchema,
  setupStepSchema,
  setupStepStateSchema,
  type SetupCompanyRequest,
  type SetupState,
  type SetupStep,
  type SetupStepState,
} from "./setup.js";

// スタッフ支払集計（P5-18 / docs/PK-SPEC-PAY.md）。
// **控除の項目は無い**（支給総額の基礎まで / PAY §0.2 MUST）。
export {
  EMPLOYMENT_TYPE_VALUES,
  PAY_UNIT_TYPE_VALUES,
  PAYOUT_PERIOD_STATUS_VALUES,
  employmentTypeSchema,
  payoutAdjustmentRequestSchema,
  payoutAggregateRequestSchema,
  payoutLineSchema,
  payoutLinesResponseSchema,
  payoutListResponseSchema,
  payoutMonthSchema,
  payoutPeriodStatusSchema,
  payoutPeriodSummarySchema,
  payRuleCreateRequestSchema,
  payUnitTypeSchema,
  staffPayProfileUpsertRequestSchema,
  type EmploymentTypeValue,
  type PayoutAdjustmentRequest,
  type PayoutAggregateRequest,
  type PayoutLine,
  type PayoutLinesResponse,
  type PayoutListResponse,
  type PayoutPeriodSummary,
  type PayRuleCreateRequest,
  type StaffPayProfileUpsertRequest,
} from "./payout.js";

// Workforce（P8-01 / P8-02 / PK-SPEC-P8 §1.3・§1.4）。
// **在留カード番号・パスポート番号・住所・生年月日を受け取る項目が無い**
// （security.md §3）。就労可否も受け取らない（§1.4 MUST）。
export {
  RESIDENCY_STATUS_TYPE_VALUES,
  SHIFT_TYPE_VALUES,
  WORK_STATUS_VALUES,
  residencyStatusTypeSchema,
  residencyUpsertRequestSchema,
  shiftTypeSchema,
  shiftUpsertRequestSchema,
  staffLedgerUpdateRequestSchema,
  workStatusSchema,
  type ResidencyStatusTypeValue,
  type ResidencyUpsertRequest,
  type ShiftTypeValue,
  type ShiftUpsertRequest,
  type StaffLedgerUpdateRequest,
  type WorkStatusValue,
} from "./workforce.js";

// プラットフォーム運営の初期開通（PF-16 / DECISIONS #240・#245）。
// **1 人目だけ。** 応答に開通 token を含めない（受け渡しはメール 1 通）。
export {
  PLATFORM_BOOTSTRAP_ERROR_CODES,
  platformBootstrapErrorSchema,
  platformBootstrapRequestSchema,
  platformBootstrapResponseSchema,
  type PlatformBootstrapError,
  type PlatformBootstrapErrorCode,
  type PlatformBootstrapRequest,
  type PlatformBootstrapResponse,
} from "./platform.js";
